### ISSUE TITLE
[FE] As a end user I want to be able to Register and Login an account so that I can keep the track of my crypto portfolio

### ISSUE THREAD

**Issue by d-chobotar** [4GeeksAcademy/pt66-crypto-sense#2]

**Comment by d-chobotar** [comment]
AC:
- [ ] User is able to register with basic authentication (username and password)
- [ ] User is able to create an account using the google integration
- [ ] The email for the account should be unique
- [ ] The username should unique
- [ ] Password criteria - (6 characters min - 15 max)

**Comment by daperk** [comment]
I added login too to this task.
